### ISSUE TITLE
Clean Ubuntu install get errors...

### ISSUE THREAD

**Issue by jdeer0618** [ecprice/newsdiffs#15]
2013-06-08 22:05:50.307:ERROR:CalledProcessError when updating http://edition.cnn.com/2013/06/06/travel/worlds-best-beach-bars/index.html
2013-06-08 22:05:50.313:ERROR:"fatal: Invalid object name 'HEAD'.\n"
2013-06-08 22:05:50.315:ERROR:Traceback (most recent call last):
  File "/home/jdeer/website/frontend/management/commands/scraper.py", line 355, in update_versions
    update_article(article)
  File "/home/jdeer/website/frontend/management/commands/scraper.py", line 301, in update_article
    article)
  File "/home/jdeer/website/frontend/management/commands/scraper.py", line 208, in add_to_git_repo
    previous = run_git_command(['show', 'HEAD:'+filename])
  File "/home/jdeer/website/frontend/management/commands/scraper.py", line 145, in run_git_command
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['git', 'show', u'HEAD:edition.cnn.com/2013/06/06/travel/worlds-best-beach-bars/index.html']' returned non-zero exit status 128

**Comment by mgummich** [comment]
Could you provide the solution for the problem? That would be wonderful because at the moment i am facing the same problem and i have no idea how to solve it.

**Comment by msbt** [comment]
@jdeer0618 @mgummich did you ever find a solution for this? trying to set it up and having the same error
