### ISSUE TITLE
Heroku?

### ISSUE THREAD

**Issue by amandabee** [ecprice/newsdiffs#37]
Has anyone successfully deployed Newsdiffs on Heroku?

**Comment by ecprice** [comment]
Not that I'm aware of.

**Comment by amandabee** [comment]
So I guess I'm about to learn something new. As I wrap my head around wrapping newsdiffs in wsgi, if you have any advice or insights, I'm all ears. Otherwise I'll just charge on ahead.

**Comment by amandabee** [comment]
I'm getting super stuck. Possibly because I don't know a thing about Django. Or Heroku ...

But [stackoverflow](http://stackoverflow.com/questions/32600341/how-to-deploy-migrate-an-existing-django-app-project-to-a-production-server?lq=1) says I need gunicorn, so I added that to my venv and then added `wsgi.py` but I'm still getting errors:

    (venv)amanda@mona:newsdiffs$ heroku local
    forego | starting web.1 on port 5000
    web.1  | [2015-09-27 18:13:57 +0000] [25481] [INFO] Starting gunicorn 19.1.1
    web.1  | [2015-09-27 18:13:57 +0000] [25481] [INFO] Listening at: http://0.0.0.0:5000 (25481)
    web.1  | [2015-09-27 18:13:57 +0000] [25481] [INFO] Using worker: sync
    web.1  | [2015-09-27 18:13:57 +0000] [25486] [INFO] Booting worker with pid: 25486
    web.1  | [2015-09-27 18:13:57 +0000] [25486] [ERROR] Exception in worker process:
    web.1  | (module)
    web.1  | : No module named newsdiffs.wsgi
    web.1  | [2015-09-27 18:13:57 +0000] [25486] [INFO] Worker exiting (pid: 25486)
    web.1  | Traceback (most recent call last):
    web.1  |     sys.exit(run())
    web.1  |     super(Application, self).run()
    web.1  |   File "/home/amanda/Public/newsdiffs/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 71, in run
    web.1  |   File "/home/amanda/Public/newsdiffs/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 169, in run
    web.1  |   File "/home/amanda/Public/newsdiffs/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 477, in manage_workers
    web.1  |     self.spawn_workers()
    web.1  |   File "/home/amanda/Public/newsdiffs/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 542, in spawn_workers
    web.1  |     time.sleep(0.1 * random.random())
    web.1  |   File "/home/amanda/Public/newsdiffs/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 209, in handle_chld
    web.1  |     self.reap_workers()
    web.1  |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
    web.1  | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

Not surprised by the errors, but not sure what to do with them, either.
